esphome:
  name: electricity-price-display
  friendly_name: "Electricity price display"

  includes:
    - "ticks.h"
    - "dithermask.h"
    - "dither.h"
    - "draw.h"

  on_boot:
    - priority: 10000  # as early as possible
      then:
        - lambda: |-
            // initialize hourly_prices with NaNs to indicate no data
            for (float& price : id(hourly_prices))
              price = NAN;

    - priority: -100  # when everything else should already be initialized
      then:
        - logger.log: "Setting up initial data update check"
        - delay: 5min
        - lambda: |-
            // if no data yet received, update display to show alert
            if (!id(prices_start_date).is_valid())
              id(epaper).update();

esp8266:
  board: nodemcuv2
  restore_from_flash: true

# Enable logging
logger:

ota:
  - platform: esphome
    password: !secret ota_password
safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Display Fallback Hotspot"
    password: !secret fallback_hotspot_password

captive_portal:


external_components:
  # As of esphome version 2024.6.2, support for WeAct 2.9" RBW epaper
  # is in an unmerged pull request
  - source: "github://pr#6226"
    components: [waveshare_epaper]

network:
  enable_ipv6: true


globals:
  - id: hourly_prices
    type: "std::array<float, 48>"
    # initialized to NaN in on_boot
    # TODO: maybe use fixed point instead; no native float in ESP8266

  - id: prices_start_date
    type: "ESPTime"
    # Initialize to a time whose is_valid() == false.
    # Invalid time means that initial data has not yet been received.
    initial_value: "ESPTime::from_epoch_utc(0)"

  - id: update_on_time_sync
    type: "bool"
    initial_value: "false"

# Home Assistant API
api:
  services:
    - service: set_prices
      variables:
        prices: float[]  # prices in cents
        start_year: int   #⎫
        start_month: int  #⎬ date of first values
        start_day: int    #⎭
      then:
        - lambda: |-
            ESP_LOGI("set_prices", "New prices received: %u items",
                     prices.size());
            ESP_LOGV(
              "set_prices", "Received prices: %s",
              [&]() {
                std::string str;
                for (float price : prices) {
                  str += ", ";
                  str += std::to_string(price);
                }
                return str;
              }().c_str() + 2);

            auto& dest = id(hourly_prices);

            if (prices.size() > dest.size())
              ESP_LOGW(
                "set_prices", "More than %u items received. Discarding rest.",
                dest.size());

            auto dest_it = dest.begin();
            auto end = dest.end();
            for (float price : prices) {
              *dest_it = price;
              if (++dest_it == end)
                break;
            }
            for (; dest_it != end; ++dest_it)
              *dest_it = NAN;

            ESPTime& start = id(prices_start_date);
            start.year = start_year;
            start.month = start_month;
            start.day_of_month = start_day;
            start.hour = start.minute = start.second = 0;
            start.recalc_timestamp_local(false);

            if (id(homeassistant_time).now().is_valid()) {
              id(epaper).update();
            }
            else {
              ESP_LOGD(
                "set_prices",
                "Clock not yet set. Waiting for time synchronization"
                " before updating display.");
              id(update_on_time_sync) = true;
            }


color:
  - id: red
    hex: "FF0000"

font:
  # note: Font rendering is terribly ugly for some fonts, such as
  # Roboto and Open Sans. Arial seems to work nicely.
  - file: "arialn.ttf"  # Arial Narrow
    id: main_font
    size: 18
    # U+2009 = thin space
    # U+200A = hair space
    glyphs: "0123456789c/kWh\u2009\u200A"
    extras:
      # "." is annoyingly small at this font size, just 1 pixel. Let's
      # use bold "."
      file: "arialnb.ttf"  # Arial Narrow bold
      glyphs: "."
  - file: "arialn.ttf"  # Arial Narrow
    id: cur_price_font
    size: 36
    glyphs: "0123456789.,-?"

image:
  - file: "mdi:robot-dead-outline"
    id: no_data_icon
    resize: 128x128

  - file: "price-alert.svg"
    type: TRANSPARENT_BINARY
    id: price_alert_icon
    resize: 50x44

spi:
  clk_pin: D1
  mosi_pin: D2

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: D4  # also LED pin; LED used as update indicator
    dc_pin: D5
    reset_pin: D6
    busy_pin: D7
    model: 2.90in3c
    rotation: 90
    update_interval: never
    lambda: "draw(it);"  # call code in draw.h


number:
  - platform: template
    id: gradient_top
    name: "Gradient top price"
    entity_category: config
    unit_of_measurement: c
    mode: box
    device_class: monetary
    icon: "mdi:gradient-vertical"
    optimistic: true
    min_value: -10000
    max_value: 10000
    step: 1
    restore_value: true
    initial_value: 40
    on_value:
      then:
        - component.update: epaper
  - platform: template
    id: gradient_bottom
    name: "Gradient bottom price"
    entity_category: config
    unit_of_measurement: c
    mode: box
    device_class: monetary
    icon: "mdi:gradient-vertical"
    optimistic: true
    min_value: -10000
    max_value: 10000
    step: 1
    restore_value: true
    initial_value: 20
    on_value:
      then:
        - component.update: epaper

switch:
  - platform: template
    id: show_past_hours_switch
    name: "Show past hours"
    icon: "mdi:chart-bar"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      then:
        - component.update: epaper
    on_turn_off:
      then:
        - component.update: epaper

  - platform: template
    id: price_warning_switch
    name: "Price warning"
    icon: "mdi:cash"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON
    on_turn_on:
      then:
        - lambda: "on_price_warning_switch_change();"
    on_turn_off:
      then:
        - lambda: "on_price_warning_switch_change();"

button:
  - platform: restart
    name: "Restart"
    entity_category: config
  - platform: safe_mode
    name: "Restart (safe mode)"
    entity_category: config

  - platform: template
    name: "Redraw screen"
    icon: "mdi:image-refresh-outline"
    entity_category: config
    on_press:
      then:
        - component.update: epaper


time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: "Europe/Helsinki"
    on_time:
      seconds: 0
      minutes: 0
      then:
        - lambda: |-
            // update display, unless we're still waiting for initial data
            if (id(prices_start_date).is_valid())
              id(epaper).update();
    on_time_sync:
      then:
        - lambda: |-
            if (id(update_on_time_sync)) {
              id(update_on_time_sync) = false;
              ESP_LOGD(
                "on_time_sync",
                "Time synchronized. Running deferred display update.");
              id(epaper).update();
            }


binary_sensor:
  - platform: status
    name: status

sensor:
  - platform: wifi_signal
    name: "WiFi RSSI"
    entity_category: diagnostic
    update_interval: 5min
