alias: "Update electricity price display"
description: >-
  Update electricity price display when display is connected or price
  sensor receives new values
trigger:
  - platform: state
    entity_id: sensor.nordpool
    attribute: tomorrow
  - platform: state
    entity_id: binary_sensor.electricity_price_display_status
    to: "on"
variables:
  entity_id: sensor.nordpool
action:
  - service: esphome.electricity_price_display_set_prices
    data: |-
      {% set start = state_attr(entity_id, "raw_today")[0].start -%}
      {
        "prices": {{ state_attr(entity_id, "today") +
                     state_attr(entity_id, "tomorrow")|default([]) }},
        "start_year": {{ start.year }},
        "start_month": {{ start.month }},
        "start_day": {{ start.day }}
      }
mode: single
